name: "build and release vscode syntax highlight"

on:
  push:
    # uncomment to release only on tags starting with 'v'
    # tags:
    #   - "v*"
    branches:
      - "main"

  workflow_dispatch:

jobs:
  npm-publish:
    name: "Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      ### Extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Extract branch name
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      ### Calculate FINAL_VERSION
      - name: Install jq
        run: sudo apt-get update && sudo apt-get --yes --force-yes install jq

      - name: Get version from npm and increment
        run: |
          set -x
          cd vscode-highlight
          PATH="$(yarn global bin):$PATH"
          yarn global add semver

          # take npm version and increment it
          PKG_NAME="$(cat package.json | jq -r .name)"
          NPM_VERSION="$(yarn info --silent "$PKG_NAME" version || true)"
          NEXT_NPM_VERSION="$(semver --increment patch "$NPM_VERSION")"
          
          # take local version
          LOCAL_VERSION="$(cat package.json | jq -r .version)"

          # take maximum of the local and NEXT_NPM versions
          MAX_VERSION="$(semver "$LOCAL_VERSION" "$NEXT_NPM_VERSION" "0.0.0" | tail -n1)"

          # save info to env
          echo "FINAL_VERSION=$MAX_VERSION" | tee -a $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" | tee -a $GITHUB_ENV
          echo "PKG_FILE=vscode-highlight/${PKG_NAME}-${MAX_VERSION}.vsix" | tee -a $GITHUB_ENV

      ### Set version
      - name: Set version to ${{ env.FINAL_VERSION }}
        run: |
          cd vscode-highlight
          yarn version --new-version ${{ env.FINAL_VERSION }} --no-git-tag-version

      ### Pack npm package
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd vscode-highlight
          npm i -g vsce
          vsce package

      ### create release
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.FINAL_VERSION }}
          name: Visual Studio Code syntax highlight ${{ env.FINAL_VERSION }}
          body: |
            Version: ${{ env.FINAL_VERSION }}
          files: |
            ${{ env.PKG_FILE }}
          draft: false
          prerelease: true

